/** Static English interface copy. Learning content remains in its source language. */
export const uiCopy = {
  accessibility: {
    skipToContent: 'Skip to content',
    home: 'Kotoba home',
    primaryNavigation: 'Primary navigation',
    mainNavigation: 'Main navigation',
    closeMenu: 'Close menu',
  },
  shell: {
    studySpace: 'STUDY SPACE',
    workspace: 'Workspace',
    localStudySpace: 'Your study space',
    study: 'Study',
    more: 'More',
    chooseStudyArea: 'Choose a study area',
    moreOfWorkspace: 'More of your workspace',
    mobileNavigation: { home: 'Home', search: 'Search', study: 'Study', review: 'Review', more: 'More' },
  },
  appearance: {
    label: 'Appearance',
    change: 'Change appearance',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
  },
  navigation: {
    home: 'Home',
    dictionary: 'Dictionary',
    kanji: 'Kanji',
    grammar: 'Grammar',
    reading: 'Reading',
    review: 'Review',
    jlpt: 'JLPT',
    notebook: 'Notebook',
    progress: 'Progress',
    settings: 'Settings',
  },
  settings: {
    preferences: 'PREFERENCES',
    title: 'Settings',
    description: 'Adjust the way your study space looks.',
    appearance: 'Appearance',
    deviceThemeNote: 'Your theme preference is stored on this device.',
    colorTheme: 'Color theme',
    lightDescription: 'A clear, warm workspace.',
    darkDescription: 'A softer view in low light.',
    systemDescription: 'Follow your device setting.',
    about: 'About this workspace',
    aboutDescription: 'Kotoba keeps your future study tools focused and local-first.',
    application: 'Application',
    currentPhase: 'Current phase',
    currentPhaseValue: 'Dictionary, kanji, and grammar',
  },
  home: {
    reviewEyebrow: 'READY WHEN YOU ARE',
    reviewsDue: '34 reviews due',
    reviewDescription: 'Keep familiar words fresh with a short review.',
    openReview: 'Open review',
    studySummary: "Today's study summary",
    dailyGoal: 'Daily goal',
    words: 'words',
    studiedToday: 'Studied today',
    studyStreak: 'Study streak',
    days: 'days',
    continueLearning: 'Continue learning',
    continueEyebrow: 'PICK UP WHERE YOU LEFT OFF',
    todaysVocabulary: "Today's vocabulary",
    vocabularyEyebrow: 'A FEW WORDS FOR TODAY',
    openDictionary: 'Open dictionary',
    jlptProgress: 'JLPT progress',
    jlptEyebrow: 'YOUR STUDY PATH',
    viewJlpt: 'View JLPT progress',
    recentlySearched: 'Recently searched',
    recentEyebrow: 'RECENT LOOKUPS',
  },
} as const
